export const fakeAPICalled_2 = {
    "placa": "INT8C36",
    "api": "2",
    "data": {
        "situacaoveiculo": "CIRCULACAO",
        "placa": "JGE8393",
        "municipio": "UBERLANDIA-MG",
        "uf": "MG",
        "renavam": "00822620308",
        "cpf_cnpj_proprietario": "08065350674",
        "tipodocumentoproprietario": "FISICA",
        "pronome": "08065350674 ROSANGELA CANDIDA DE S ARAUJO",
        "licdata": "27/12/2018",
        "dataemissaocrv": "27/12/2018",
        "chassi": "9BFZF10B248184190",
        "tipodocumentofaturado": "JURIDICA",
        "cpfcnpjfaturado": "00003228000216",
        "uffaturado": "DF",
        "tipodocumentoimportadora": "",
        "tiporemarcacaochassi": "NORMAL",
        "marcamodelocompleto": "FORD/FIESTA",
        "marca": "FORD",
        "modelo": "FIESTA",
        "veianofabr": "2004",
        "veianomodelo": "2004",
        "tipo": "AUTOMOVEL",
        "carroceria": "INEXISTENTE",
        "cor": "PRATA",
        "especie": "PASSAGEIRO",
        "veicategoria": "PARTICULAR",
        "combustivel": "GASOLINA",
        "potencia": "66",
        "cilindrada": "999",
        "capacidadecarga": "0",
        "codigocategoria": "1",
        "codigocor": "10",
        "codigomarca": "159903",
        "codigotipo": "6",
        "veiprocedencia": "NACIONAL",
        "capacidadepassag": "5",
        "motoragregados": "CAJA48184190",
        "motor": "CAJA48184190",
        "numero_caixacambio": "",
        "numero_carroceria": "",
        "numero_eixotraseirodif": "",
        "numero_terceiroeixo": "",
        "cmt": "0",
        "pbt": "150",
        "eixos": "2",
        "restricaofinan": "",
        "restricaonomeagente": "",
        "restricaoarrendatario": "",
        "restricaodatainclusao": "",
        "numerocontratofinanceira": "",
        "codigoagentefinanceiro": "",
        "datavigenciacontratofinanceira": "",
        "existedebitodeipva": "EXISTE DEBITO IPVA E OU LICENCIAMENTO",
        "existedebitomulta": "EXISTE DEBITO DE MULTA",
        "debipva": "0,00",
        "existedebitodelicenciamento": "EXISTE DEBITO DE LICENCIAMENTO",
        "existedebitodelicenciamentovl": "150,47",
        "valortotaldebitomulta": "0,00",
        "existedebitodedpvat": "NAO EXISTE DEBITO DE DPVAT",
        "dpvat": "0,00",
        "outras_restricoes_01": "NADA CONSTA",
        "outras_restricoes_02": "NADA CONSTA",
        "outras_restricoes_03": "NADA CONSTA",
        "outras_restricoes_04": "NADA CONSTA",
        "pronomeanterior": "",
        "restricaocpfcnpjarrendatar": "",
        "intencaorestricaofinan": "",
        "intencaonomeagente": "",
        "intencaonomefinanc": "",
        "intencaocpfcnpjfinanc": "",
        "intencaodatainclusao": "",
        "debdersa": "",
        "debder": "",
        "debdetran": "",
        "debcetesb": "",
        "debrenainf": "",
        "debmunicipais": "0,00",
        "debpolrodfed": "",
        "resfurto": "NADA CONSTA",
        "resguincho": "NADA CONSTA",
        "resadministrativa": "NADA CONSTA",
        "resjudicial": "NADA CONSTA",
        "restributaria": "NADA CONSTA",
        "resrenajud": "NADA CONSTA",
        "resambiental": "",
        "licexelic": "",
        "ccomunicacaovenda": "NAO CONSTA COMUNICACAO DE VENDAS",
        "ccomunicinclusao": "",
        "tipodoccomprador": "",
        "cpfcnpjcomprador": "",
        "datavenda": "",
        "notafiscal": "",
        "protocolodetran": "",
        "inspecaoano": "",
        "inspecaocentro": "",
        "inspecaodata": "",
        "inspecaoselo": "",
        "inspecaostatus": "",
        "codigofinanceira": "",
        "datainclusaointencaotrocafinanceira": "",
        "datalimiterestricaotributaria": ""
    }
};
export const fakeAPICalled_LEILAO = {
    "dados_veiculo": {
        "marcamodelo": "GM S10 LTZ DD4A",
        "anofabricacaomodelo": 2015,
        "placa": "AWH4I48",
        "chassi": "9BG148MK0FC435203",
        "cor": "BRANCA"
    },
    "leilao": {
        "descricaoretorno": "Consta Registro de Leilao para o veiculo informado",
        "qtdleilao": "2",
        "registro": [
            {
                "leiloeiro": "NAO INFORMADO",
                "lote": "2379",
                "quantidaderegistro": null,
                "identificacaoveiculo": null,
                "idleilao": "1",
                "identificacaolote": null,
                "marcamodelo": "S10 LTZ 2.8 TDI",
                "anofabricacaomodelo": "2015",
                "placa": "AWH4848",
                "chassi": "9BG148MK0FC435203",
                "cor": "BRANCA",
                "condicaogeraldoveiculo": "NAO DIVULGADO",
                "situacaogeraldochassi": "NAO DIVULGADO",
                "patio": "NAO INFORMADO",
                "dataleilao": "30/11/2017",
                "comitente": "BRADESCO SEGUROS S/A DTSN",
                "classificacao": "NAO FOI POSSIVEL CLASSIFICAR",
                "foto1": "NAO INFORMADO",
                "foto2": "NAO INFORMADO",
                "foto3": "NAO INFORMADO",
                "foto4": "NAO INFORMADO"
            },
            {
                "leiloeiro": "N/C",
                "lote": "0",
                "quantidaderegistro": null,
                "identificacaoveiculo": null,
                "idleilao": "2",
                "identificacaolote": null,
                "marcamodelo": "S10 LTZ DD4A",
                "anofabricacaomodelo": "2015",
                "placa": "AWH4848",
                "chassi": "9BG148MK0FC435203",
                "cor": "BRANCA",
                "condicaogeraldoveiculo": "NAO INFORMADO",
                "situacaogeraldochassi": "NAO INFORMADO",
                "patio": "NAO INFORMADO",
                "dataleilao": "30/11/2017",
                "comitente": "BRADESCO SEGUROS S/A",
                "classificacao": "NAO FOI POSSIVEL CLASSIFICAR",
                "foto1": "NAO INFORMADO",
                "foto2": "NAO INFORMADO",
                "foto3": "NAO INFORMADO",
                "foto4": "NAO INFORMADO"
            }
        ]
    },
    "analise_risco": {
        "descricaoretorno": "PESQUISA EFETUADA COM SUCESSO",
        "indicerisco": "2",
        "parecer": "VEICULO COM RISCO MEDIO DE COMERCIALIZACAO"
    }
};
export const fakeAPICalled_1 = {
    "placa": "INT1C45",
    "chassi": "9C2KC08507R050947",
    "fabricante": "HONDA",
    "modelo": "CG 150 TITAN ES",
    "ano_fabricacao": 2007,
    "ano_modelo": 2007,
    "combustivel": "GASOLINA",
    "tipo_veiculo": "MOTOCICLETA",
    "especie": "PASSAGEIRO",
    "cor": "PRETA",
    "tipo_carroceria": "NAO APLICAVEL",
    "nacionalidade": "NACIONAL",
    "numero_motor": "KC08E57050947",
    "potencia": null,
    "carga": null,
    "numero_carroceria": null,
    "numero_caixa_cambio": null,
    "numero_eixo_traseiro": null,
    "numero_terceiro_eixo": null,
    "quantidade_eixo": "0",
    "cilindradas": 149,
    "capacidade_max_tracao": null,
    "peso_bruto_total": null,
    "quantidade_lugares": 2,
    "tipo_montagem": 1,
    "uf_jurisdicao": "RS",
    "uf_faturado": "RS",
    "cidade": "GENTIL"
};

export const fakeMainAPICalled = {
    MARCA: '',
    MODELO: '',
    ano: ''
};